# Generated by Django 5.1.6 on 2026-04-17 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_report_description_report_feedback_id_and_more'),
        ('projects', '0005_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='description',
        ),
        migrations.RemoveField(
            model_name='report',
            name='feedback_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='target_type',
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='pending', max_length=20),
        ),
    ]
