# Generated by Django 5.1.6 on 2026-03-31 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='clarity',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='design',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='presentation_impact',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='research_depth',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='technical_skill',
        ),
    ]
