# Generated by Django 5.1.6 on 2026-04-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_helpfulvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpfulvote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Helpful'), (-1, 'Not Helpful')]),
        ),
    ]
